---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0494aa7fa1314e98913a41227d8f0a515b2c1049  # frozen: 0.38.2
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/executablebooks/mdformat
    rev: 2d496dbc18e31b83a1596685347ffe0b6041daf0  # frozen: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm

  - repo: https://github.com/hadolint/hadolint
    rev: 2eece55955ced00200be9729e9728cb7dacca505  # frozen: v2.15.1
    hooks:
      - id: hadolint
