---
name: Cleanup Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 15 * *"

concurrency:
  group: cleanup-images-${{ github.ref }}
  cancel-in-progress: false

env:
  IMAGE_NAME: minecraft-skyfactory4

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      packages: write
      contents: read

    steps:
      - name: Cleanup Docker Images
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          delete-partial-images: true
          delete-untagged: true
          keep-n-tagged: 2
          older-than: 30 days
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ env.IMAGE_NAME }}
          owner: ${{ github.repository_owner }}

      - name: Send notification to Discord.
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
        if: always()
        with:
          title: ${{ env.IMAGE_NAME }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
